blank_issues_enabled: false
contact_links:
  - name: DSMR-reader Docker issue
    url: https://github.com/xirixiz/dsmr-reader-docker/issues
    about: If you are running into issues running DSMR-reader at all in Docker, checkout Xirixiz's awesome project for more information and help!
  - name: DSMR-reader Home Assistant Add-On issue
    url: https://github.com/sanderdw/hassio-addons/issues
    about: Can't get DSMR-reader working in Home Assistant as Add-On? You probably used Sander de Wildt's plugin. Check out this link for more information!
